### ISSUE TITLE
Slack integrations

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Docs#12]
@alice-sieve/folks I have integrated

- GitHub
  - `github` for everything
- Google Calendar
  - posting meetings we have scheduled or reminders
  - Calendar names is internship and all of you have access, use wisely
- Hangouts
   - `/hangouts` will create a hangouts call
- Paper
   - `paper new paper-name` will create a dropbox paper
   - `paper paper-name` will let you search for created paper
- Zoom
   - `/zoom` will create a zoom call

Every work created on GitHub will be posted in the internship Slack channel, no need for re-pinging, that's enough as a ping notification.

**Comment by bymayanksingh** [comment]
ack

**Comment by sujay0399** [comment]
ack

**Comment by Aashi15bansal** [comment]
ack
