### ISSUE TITLE
Review the JOSS submissions

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Docs#13]
- https://github.com/alice-sieve/MapReduce-Genomics
- https://github.com/alice-sieve/LK-Patches-Patcher
- https://github.com/alice-sieve/Funneling-Research
- https://github.com/alice-sieve/How-Open-is-Open-Source
- https://github.com/alice-sieve/FAUMachine-Clusters
- https://github.com/alice-sieve/Humanless-OnSite-Surveys
- https://github.com/alice-sieve/distcc-HPC-Cluster
- https://github.com/alice-sieve/Humanless-Oncalls

@alice-sieve/folks can you please review the text I have written here. I am planning only these many submissions for JOSS, feel free PRing, make sure you tag me for review. 

Read on how https://github.com/openjournals/joss-reviews/issues journal is doing review for the submissions. I want full acceptance. I also suggest you reading that losing submissions, shouldn't be a sour grapes case. Please check the names as well, people who are putting effort for any implementation will be co authors among more advantages.

**Comment by bymayanksingh** [comment]
Joss reviewer guidelines : [docs](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)
