### ISSUE TITLE
Let me know Publications you know

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Docs#14]
@alice-sieve/folks Can you write publication which I haven't curated as a comment on the ticket? Domains are

- Distributed Computing
- OS
- Linux Kernel
- Open Source
- Genomics
- Statistics
- Market Research
- Economics
- Data visualisations
- Data is little thing in few of these

There are so many journals, publications, I don't think I have curated all. Let me know if you know which isn't listed. I want a large useful presence on different publication for the work.

**Comment by Aashi15bansal** [comment]
@tapaswenipathak  Where can I find the publication list of yours ?

**Comment by tapaswenipathak** [comment]
On Fri, Jul 19, 2019 at 8:32 AM Aashi15bansal <notifications@github.com> wrote:
>
> @tapaswenipathak Where can I find the publication list of yours ?

https://paper.dropbox.com/doc/PapersArticles-Timelines--AhN7wgBd5uNEZ4tUWAFuJgjUAQ-Uw4JOA5J3YTNY6aRamEs9
https://github.com/alice-sieve/Research-Paper-Publications
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by tapaswenipathak** [comment]
👋ping peeps.
