### ISSUE TITLE
Reminder: Note The deadlines

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Docs#18]
As I have spoken and said in calls in past multiple times, throwing that straight out now, if we miss the deadlines we miss publications! Every work is a publication, which is accepted and is on me. Getting more people in for easing out the pressure. Prioritise the work, if things get boring let me know I will help you taking work as fun! 

![](https://media.giphy.com/media/l0IpXxDMKy7O17lug/source.gif)

**Comment by Aashi15bansal** [comment]
ack
