### ISSUE TITLE
Next Sunday Deadlines

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Docs#19]
![](https://media.giphy.com/media/l1KVcrdl7rJpFnY2s/source.gif)

- Usernames, Paper Docs are priority - @alice-sieve/folks, @tapaswenipathak 
- Device work - @KevinChittilapilly @mayankchauhan971 @NiharikaMessi 
- Linux Kernel work - @amit-sharma-9 @bhaskartalla @code-monk08 @mamtashukla @Aashi15bansal @tapaswenipathak 
- Kick off Econ publications - @charusinha @code-monk08  @tapaswenipathak 
- Visualisations & Notebooks - @code-monk08 @prateekmaj21 @prabalgoel @shah-aman  @sdhrth @sujaykumarreddy @ucalyptus 
- Django work - @nightwarrior-xxx 
- Genomics Paper work - @sujaykumarreddy @tapaswenipathak 
- Blogging - @bhaskartalla @NiharikaMessi @sakshivij   @tapaswenipathak 
- Social Media Account handling - @priyankachou

**Comment by sujay0399** [comment]
ack

**Comment by Aashi15bansal** [comment]
ack

**Comment by ucalyptus** [comment]
ack

**Comment by bymayanksingh** [comment]
ack

**Comment by tapaswenipathak** [comment]
- https://github.com/alice-sieve/Intern-Ids/issues/24, https://github.com/alice-sieve/Docs/issues/14, https://github.com/alice-sieve/Docs/issues/13, https://github.com/alice-sieve/Intern-Ids/issues/15 - @alice-sieve/folks 
- https://github.com/alice-sieve/Economics/issues/4 - @charusinha @tapaswenipathak 
- https://github.com/alice-sieve/Linux-Kernel/issues/90, https://github.com/alice-sieve/Linux-Kernel/issues/89, https://github.com/alice-sieve/Linux-Kernel/issues/88 - @Aashi15bansal @tapaswenipathak 
- https://github.com/alice-sieve/Linux-Kernel/issues/87, https://github.com/alice-sieve/Linux-Kernel/issues/86 - @mamtashukla @tapaswenipathak 
- https://github.com/alice-sieve/Open-Source/issues/16, https://github.com/alice-sieve/Open-Source/issues/13 - @nightwarrior-xxx 
- https://github.com/alice-sieve/Non-Tech-Tasks/issues/3 - @priyankachou 
- https://github.com/alice-sieve/iot-interns/issues/3, https://github.com/alice-sieve/iot-interns/issues/2, https://github.com/alice-sieve/Non-Tech-Tasks/issues/3 - @KevinChittilapilly @mayankchauhan971 @NiharikaMessi 
- https://github.com/tapaswenipathak/TheLesserNumber/issues/80, https://github.com/alice-sieve/Open-Source/issues/15 - @code-monk08 @prabalgoel @ucalyptus @sdhrth @nightwarrior-xxx @shah-aman @prateekmaj21 @amit-sharma-9
- https://github.com/alice-sieve/Open-Source/issues/12 - @NiharikaMessi 
- https://github.com/alice-sieve/Open-Source/issues/6 - @code-monk08 
- Blog writing (will create drafts from today, me reviewing few initial before publishing) - @tapaswenipathak and others.
- https://github.com/alice-sieve/FAUMachine-Fault-Injection-Clusters, https://github.com/alice-sieve/distcc-HPC-Cluster - @tapaswenipathak

**Comment by tapaswenipathak** [comment]
@alice-sieve/folks Write on the ticket till today end of day. 

- Tickets assigned
- Tickets completed
- Tickets remaining (What's the plan?)
- Extra tickets taken out of interest

**Comment by nightwarriorftw** [comment]
- Tickets assigned
    + https://github.com/alice-sieve/Open-Source/issues/16
    + https://github.com/alice-sieve/Open-Source/issues/13
    + https://github.com/tapaswenipathak/TheLesserNumber/issues/80
    + https://github.com/alice-sieve/Open-Source/issues/15

- Tickets completed
    + https://github.com/alice-sieve/Open-Source/issues/16

- Pull Requests
    + https://github.com/alice-sieve/Open_Source_Orgs_Viz/pull/1

- Tickets remaining
    + https://github.com/alice-sieve/Open-Source/issues/13
    + https://github.com/tapaswenipathak/TheLesserNumber/issues/80
    + https://github.com/alice-sieve/Open-Source/issues/15

- Plan
 I will try to complete pending tasks in the upcoming week.

**Comment by Aashi15bansal** [comment]
--  Tickets Assigned :

https://github.com/alice-sieve/tapaswenipathak.blog/issues/4
https://github.com/tapaswenipathak/TheLesserNumber/issues/103
https://github.com/alice-sieve/Linux-Kernel/issues/90
https://github.com/alice-sieve/Economics/issues/5

-- Tickets Completed :
https://github.com/alice-sieve/Economics/issues/5

-- Tickets in-progress 
https://github.com/alice-sieve/Linux-Kernel/issues/90

--Tickets waiting on others:
https://github.com/alice-sieve/tapaswenipathak.blog/issues/4

--Tickets open
https://github.com/tapaswenipathak/TheLesserNumber/issues/103

**Comment by bymayanksingh** [comment]
Tickets Assigned:

- https://github.com/alice-sieve/Open-Source/issues/6 
- https://github.com/tapaswenipathak/TheLesserNumber/issues/80
- https://github.com/alice-sieve/Open-Source/issues/15

Tickets Completed:
- https://github.com/alice-sieve/Open-Source/issues/6 
check status here:[alice-sieve/Open-Source/tree/API-Wrapper-code-monk08](https://github.com/alice-sieve/Open-Source/tree/API-Wrapper-code-monk08/API%20Wrapper)

Pull Request:
- https://github.com/alice-sieve/Linux-Kernel/pull/97
