### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Docs#28]
- As of now everything is here and there, mostly where tickets are cut. The relevant work should be present in the correct repository created wrt for the title. Ask me any question you have or doc you require, all writeups should be in the respective repositories.
- All websites and visualisations should have a screenshot, gifs, videos, I haven't reviewed any of the visualisation, I require 3D or multi year visualisations minimum
- Close any open tickets, there are hell lot of tickets open on my name, close the ticket for which the work has been submitted and merged.

Deadline - Monday end of day.

**Comment by prateekmaj21** [comment]
for the notebooks with out any screen shot , do I open the notebook and take screenshots and add them?

**Comment by tapaswenipathak** [comment]
On Sun, Aug 18, 2019 at 6:14 PM Prateek Majumder
<notifications@github.com> wrote:
>
> for the notebooks without any screenshot, do I open the notebook and take screenshots and add them?

Run the notebooks would be appropriate I think. I am there in Slack
channel, lemme know if you have any questions.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Thanks,
Tapasweni

**Comment by tapaswenipathak** [comment]
No direct pushes on main line branch, I am blocking pushes.

**Comment by tapaswenipathak** [comment]
Only create PRs.

**Comment by tapaswenipathak** [comment]
@prateekmaj21
