### ISSUE TITLE
Econ Document

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Docs#3]
Can you submit the ECon doc in a day? You can write on the ticket, make sure only I have the auth.

**Comment by charusinha** [comment]
Okay yes. I am done with it almost. I will submit today i.e July 13 by the end of the day.

**Comment by tapaswenipathak** [comment]
https://paper.dropbox.com/doc/Proposal-for-Econ.--Ag6jRsD8Tg4yoUL8m9DoZv5lAQ-yGkJltbXwV88hnIBVtSjU
