### ISSUE TITLE
Linux Document

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Docs#4]
Can you submit the Linux doc in a day? You can write on the ticket, make sure only I have the auth.

**Comment by bymayanksingh** [comment]
will submit by eod

**Comment by bymayanksingh** [comment]
@tapaswenipathak I am done with the summary, already invited u couple of days back.

**Comment by tapaswenipathak** [comment]
https://paper.dropbox.com/doc/Linux-Testing-Summary--Ag5hbS85v6LFiVUd20wqp7rbAg-cBJVTII2XoHrDMNlTFdbd
