### ISSUE TITLE
Let people you know, know!

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Docs#5]
@alice-sieve/folks I am on a look out for more interns, you get extra compensation/stipend for putting effort for letting people know about the internship, just let them know they should  set a quick call using https://calendly.com/tapaswenipathak.

Internships => https://github.com/tapaswenipathak/Internship#internships.

**Comment by nightwarriorftw** [comment]
I will inform some of my friends

**Comment by ucalyptus** [comment]
I will inform my friends
