### ISSUE TITLE
Work till next Sunday

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Docs#8]
@alice-sieve/folks 

![](https://media.giphy.com/media/u84Lw8d6jQNhe/giphy.gif)

- No Notebooks/Visualisations are remaining - @Aashi15bansal @dhirensr @kumar-hardik @shah-aman @ucalyptus @prateekmaj21  
- We should have a device assembled or bought - @KevinChittilapilly @mayankchauhan971 
- All Linux Patch parsing tickets are done - @code-monk08 
- We should have substantial number of blogs written w/ iterating on graphs, charts, GIFs - @Aashi15bansal @NiharikaMessi @prateekmaj21  
- We have few more people and ECon work list finalising the titles of publications - @charusinha 
- Give a patch all static analyser are running - @mamtashukla 
- Django Website generic format is present, required for multiple tickets  - @nightwarrior-xxx 
- You will help in writing papers - @bhaskartalla 
- We have a branch related Genomics and the lesser number work as discussed - @sujaykumarreddy
- Finish paperwork https://paper.dropbox.com/doc/Meeting-notes-Prateek-Majumder-and-Tapasweni-Pathak--Ag~4fzLlhWVCP0bfYNuEEcOWAQ-9zMmQexcAxQl7adWwpPws - @prateekmaj21  

You all should have closed few tickets assigned on your name as per priority.

**Comment by tapaswenipathak** [comment]
Tickets -

- https://github.com/tapaswenipathak/TheLesserNumber/issues/80, https://github.com/tapaswenipathak/TheLesserNumber/issues/70, https://github.com/alice-sieve/Linux-Kernel/issues/16, https://github.com/alice-sieve/Open-Source/issues/16, https://github.com/alice-sieve/Open-Source/issues/15, https://github.com/alice-sieve/Open-Source/issues/7 -  @Aashi15bansal @dhirensr @kumar-hardik @shah-aman @ucalyptus
- https://github.com/alice-sieve/iot-interns/issues/6, https://github.com/alice-sieve/iot-interns/issues/2, https://github.com/alice-sieve/iot-interns/issues/1 - @KevinChittilapilly @mayankchauhan971
- https://github.com/alice-sieve/Linux-Kernel/issues/23, https://github.com/alice-sieve/Linux-Kernel/issues/22, https://github.com/alice-sieve/Linux-Kernel/issues/21, https://github.com/alice-sieve/Linux-Kernel/issues/17 - @code-monk08 
- https://github.com/alice-sieve/tapaswenipathak.blog/issues/4 - @Aashi15bansal @NiharikaMessi
- https://github.com/alice-sieve/Economics/issues/4 - @charusinha 
- https://github.com/alice-sieve/Linux-Kernel/issues/79 - @mamtashukla 
- https://github.com/tapaswenipathak/TheLesserNumber/issues/1 - @nightwarrior-xxx 
- https://paper.dropbox.com/doc/bhaskar-tapasweni-writing--Ag1aiQAI9JXjoUpOEQpuKJFnAg-K4HHpyFduB9firOgUFQs3 - @bhaskartalla 
- https://github.com/tapaswenipathak/JHEPC-19/issues/3, https://github.com/tapaswenipathak/JHEPC-19/issues/5, https://paper.dropbox.com/doc/Genomics-Paper--Ag4p0J9DM7zTNW5zkKJ_kh9oAQ-5XaKAE4shFGG8GDFPBxCq - @sujaykumarreddy

**Comment by nightwarriorftw** [comment]
- Assigned Issues
https://github.com/tapaswenipathak/TheLesserNumber/issues/1
- Pull Request 
https://github.com/tapaswenipathak/TheLesserNumber/pull/106
